name: Test Bash Script

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test:
    name: Run Script
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1 # https://github.com/actions/checkout

      - name: Run Bash Script
        run: |
          mkdir example-project
          mv init.sh example-project/init.sh
          cd example-project
          chmod +x init.sh
          ./init.sh "TestApp" "TestNamespace" "${{ github.head_ref }}" "12345" "23456" "34567" "45678"
