name: Test & lint PHP codebase

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '**.php'
      - 'src/composer.json'
      - 'src/composer.lock'
      - 'src/phpunit.xml'
      - 'src/.env.ci'

jobs:
  test-and-lint-php:
    name: Test & lint PHP codebase
    timeout-minutes: 10
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-24.04
    env:
      # renovate: datasource=github-releases depName=php packageName=containerbase/php-prebuild
      PHP_VERSION: 8.4.16

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1 # https://github.com/actions/checkout

      - name: Cache dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0 # https://github.com/actions/cache
        with:
          path: vendor
          key: ${{ runner.os }}-composer-dependencies-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-dependencies

      - name: Setup PHP
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # 2.36.0 # https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_pgsql, intl
          coverage: none

      - name: Install Composer dependencies
        working-directory: src
        run: composer install --prefer-dist --no-interaction

      - name: Run PHP linter
        working-directory: src
        run: composer cs

      - name: Execute tests
        working-directory: src
        run: |
          cp .env.ci .env
          php artisan test --colors=always
